name: CRC2_daily_destroy
on:
  schedule:
    # Runs destroy at 5:15 PM Pacific (01:15 AM UTC) every T-Sa
    - cron: '15 1 * * 2-6'
jobs:
  daily_destroy:
    runs-on: ubuntu-latest
    
    # Set working directory and shell
    defaults:  
      run:
        shell: bash
        working-directory: terraform  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve

      - name: Testing Logs Destroy
        id: log_destroycode
        run: echo ${{ steps.destroy.outputs.exitcode }}  

      - name: Alert if Error
        id: alert_if_error 
        if: ${{ steps.destroy.outputs.exitcode != 0 }} 
        run: curl https://events.pagerduty.com/integration/e7fceb8afa2c410cd0c72070ef101e1d/enqueue
  
